### ISSUE TITLE
KeyError: 'paging' on get_file_list()

### ISSUE THREAD

**Issue by nanpuhaha** [sebseager/slack-exporter#15]
```python
D:\slack-exporter> python exporter.py -o ./json --json -c -r --files
...
Writing output to D:\slack-exporter\json\slack_export_10-31-2022_221332\channel_A1B2C3D4E5F.json
Writing output to D:\slack-exporter\json\slack_export_10-31-2022_221332\channel-replies_A1B2C3D4E5F.json
...
Traceback (most recent call last):
  File "D:\slack-exporter\exporter.py", line 547, in <module>
    save_files(out_dir)
  File "D:\slack-exporter\exporter.py", line 404, in save_files
    for file_info in get_file_list():
  File "D:\slack-exporter\exporter.py", line 152, in get_file_list
    total_pages = json_data["paging"]["pages"]
KeyError: 'paging'
```

**Comment by TheSteveHan** [comment]
Check that you have the right scope. for me I'm missing files:read in my bot

Here's the json_data object.
{'ok': False, 'error': 'missing_scope', 'needed': 'files:read', 'provided': 'identify,channels:history,groups:history,im:history,mpim:history,channels:read,groups:read,im:read,mpim:read,users:read'}
